/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionale.GUI;
import gestionale.GUI.Main_Frame;
import gestionale.Assistito;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;

/**
 *
 * @author franc
 */
public class Frame_ExistsCustomer extends Main_Frame {

    /**
     * Creates new form Frame_ExistsCustomer
     */
    public Frame_ExistsCustomer() {
        initComponents();
    }
    
    public void showFrame(){
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_indirizzo = new javax.swing.JLabel();
        label_cittàDiResidenza = new javax.swing.JLabel();
        inp_cittàDiResidenza = new javax.swing.JTextField();
        button_salva = new javax.swing.JButton();
        data_assistito = new javax.swing.JLabel();
        data_errori = new javax.swing.JLabel();
        label_datiAssistito = new javax.swing.JLabel();
        label_errori = new javax.swing.JLabel();
        inp_cod_fiscale = new javax.swing.JTextField();
        inp_nome = new javax.swing.JTextField();
        inp_indirizzoDiResidenza = new javax.swing.JTextField();
        inp_cognome = new javax.swing.JTextField();
        label_cod_fiscale = new javax.swing.JLabel();
        label_nome = new javax.swing.JLabel();
        label_cognome = new javax.swing.JLabel();
        button_salva1 = new javax.swing.JButton();
        label_dataDiNascita = new javax.swing.JLabel();
        inp_dataDiNascita = new javax.swing.JSpinner();

        label_indirizzo.setText("Indirizzo");

        label_cittàDiResidenza.setText("Città di residenza");

        inp_cittàDiResidenza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inp_cittàDiResidenzaActionPerformed(evt);
            }
        });

        button_salva.setText("Salva");
        button_salva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_salvaActionPerformed(evt);
            }
        });

        label_datiAssistito.setText("Dati assistito corrente");

        label_errori.setText("Errori");

        inp_cod_fiscale.setToolTipText("Codice Fiscale");
        inp_cod_fiscale.setActionCommand("<Not Set>");

        inp_indirizzoDiResidenza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inp_indirizzoDiResidenzaActionPerformed(evt);
            }
        });

        inp_cognome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inp_cognomeActionPerformed(evt);
            }
        });

        label_cod_fiscale.setText("Codice Fiscale");

        label_nome.setText("Nome");

        label_cognome.setText("Cognome");

        button_salva1.setText("Modifica");
        button_salva1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_salva1ActionPerformed(evt);
                button_edit1ActionPerformed(evt);
            }
        });

        label_dataDiNascita.setText("Data di Nascita");

        inp_dataDiNascita.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        inp_dataDiNascita.setEditor(new javax.swing.JSpinner.DateEditor(inp_dataDiNascita, "dd/MM/yyyy"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_cod_fiscale, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button_salva1))
                            .addComponent(label_cognome, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_indirizzo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inp_indirizzoDiResidenza, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(inp_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(inp_cod_fiscale, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(inp_cognome, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(label_cittàDiResidenza, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inp_cittàDiResidenza, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(button_salva)
                            .addComponent(label_dataDiNascita, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inp_dataDiNascita))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(data_errori, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                            .addComponent(label_datiAssistito, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_errori, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(data_assistito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(label_cod_fiscale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_datiAssistito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(data_assistito, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inp_cod_fiscale, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_nome)
                            .addComponent(button_salva1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inp_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(label_cognome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inp_cognome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(label_indirizzo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inp_indirizzoDiResidenza, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_errori)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data_errori, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_cittàDiResidenza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inp_cittàDiResidenza, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_dataDiNascita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inp_dataDiNascita, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(button_salva)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inp_cittàDiResidenzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inp_cittàDiResidenzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inp_cittàDiResidenzaActionPerformed

    private void button_salvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_salvaActionPerformed
        //inizializzazione gestione 
        Date date = (Date) inp_dataDiNascita.getValue();
        LocalDate dataDiNascita = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        if((inp_cod_fiscale.getText() != null) && 
           (controller.verifyCodFisc(inp_cod_fiscale.getText(), inp_nome.getText(), inp_cognome.getText(), 
            dataDiNascita))){
                Assistito assistito = new Assistito(inp_cod_fiscale.getText(), inp_nome.getText(), inp_cognome.getText(), inp_indirizzoDiResidenza.getText(), inp_cittàDiResidenza.getText(), dataDiNascita);
                controller.salva(assistito);
                data_assistito.setText(assistito.toString());
        }
        else{
            data_errori.setText("Il codice fiscale non può essere vuoto oppure non è valido");
        }
    }//GEN-LAST:event_button_salvaActionPerformed

    private void inp_indirizzoDiResidenzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inp_indirizzoDiResidenzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inp_indirizzoDiResidenzaActionPerformed

    private void inp_cognomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inp_cognomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inp_cognomeActionPerformed

    private void button_salva1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_salva1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_salva1ActionPerformed

    private void button_edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_edit1ActionPerformed
        // TODO add your handling code here:
        Assistito assistito;
       
        if((assistito = controller.edit(inp_cod_fiscale.getText()))!=null){
            inp_nome.setText(assistito.getAn_nome());
            inp_cognome.setText(assistito.getAn_cognome());
            inp_indirizzoDiResidenza.setText(assistito.getAn_indirizzo());
            inp_cittàDiResidenza.setText(assistito.getAn_cittaDiResidenza());
            Date date = Date.from(
            assistito.getAn_dataDiNascita().atStartOfDay(ZoneId.systemDefault()).toInstant()
            );
            inp_dataDiNascita.setValue(date);
        }
        else{
            System.out.println("no non esiste");
        }
    }//GEN-LAST:event_button_edit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_ExistsCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_ExistsCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_ExistsCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_ExistsCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_ExistsCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_salva;
    private javax.swing.JButton button_salva1;
    private javax.swing.JLabel data_assistito;
    private javax.swing.JLabel data_errori;
    private javax.swing.JTextField inp_cittàDiResidenza;
    private javax.swing.JTextField inp_cod_fiscale;
    private javax.swing.JTextField inp_cognome;
    private javax.swing.JSpinner inp_dataDiNascita;
    private javax.swing.JTextField inp_indirizzoDiResidenza;
    private javax.swing.JTextField inp_nome;
    private javax.swing.JLabel label_cittàDiResidenza;
    private javax.swing.JLabel label_cod_fiscale;
    private javax.swing.JLabel label_cognome;
    private javax.swing.JLabel label_dataDiNascita;
    private javax.swing.JLabel label_datiAssistito;
    private javax.swing.JLabel label_errori;
    private javax.swing.JLabel label_indirizzo;
    private javax.swing.JLabel label_nome;
    // End of variables declaration//GEN-END:variables
}
