/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionale.GUI;
import gestionale.GUI.Frame_NewCustomer;
import gestionale.Controller;
/**
 *
 * @author franc
 */
public class Main_Frame extends javax.swing.JFrame {

    Controller controller = new Controller();
    
    /**
     * Creates new form Main_Frame
     */
    public Main_Frame() {
        initComponents();
        controller.carica();
        
    }

    public void showMainFrame(){
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Clients = new javax.swing.JMenu();
        jMenuItem_Clienti_Nuovo = new javax.swing.JMenuItem();
        jMenuItem_Clienti_edit = new javax.swing.JMenuItem();
        jMenu_Fornitori = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu_Help = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu_Clients.setText("Clienti");

        jMenuItem_Clienti_Nuovo.setText("Nuovo");
        jMenuItem_Clienti_Nuovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Clienti_NuovoActionPerformed(evt);
            }
        });
        jMenu_Clients.add(jMenuItem_Clienti_Nuovo);

        jMenuItem_Clienti_edit.setText("Modifica");
        jMenuItem_Clienti_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Clienti_editActionPerformed(evt);
            }
        });
        jMenu_Clients.add(jMenuItem_Clienti_edit);

        jMenuBar1.add(jMenu_Clients);

        jMenu_Fornitori.setText("Fornitori");
        jMenuBar1.add(jMenu_Fornitori);

        jMenu1.setText("Contabilità");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Prestazioni");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consultazioni");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Strumenti");
        jMenuBar1.add(jMenu4);

        jMenu_Help.setText("Help");
        jMenuBar1.add(jMenu_Help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_Clienti_NuovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Clienti_NuovoActionPerformed
        // TODO add your handling code here:
        Frame_NewCustomer nuovo = new Frame_NewCustomer();
        nuovo.showFrame();
    }//GEN-LAST:event_jMenuItem_Clienti_NuovoActionPerformed

    private void jMenuItem_Clienti_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Clienti_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_Clienti_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_Clienti_Nuovo;
    private javax.swing.JMenuItem jMenuItem_Clienti_edit;
    private javax.swing.JMenu jMenu_Clients;
    private javax.swing.JMenu jMenu_Fornitori;
    private javax.swing.JMenu jMenu_Help;
    // End of variables declaration//GEN-END:variables
}
